en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Serene Lake PTSA. All Rights Reserved." 
  title: "Serene Lake PTSA"
  params:
    description: "Serene Lake Elementary PTSA - Mukilteo School District"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Join Us!"
      link: "https://slptsa.givebacks.com/shop"
    footer_cta:
      text: "Join us"
      link: "https://slptsa.givebacks.com/shop"
